source ~/.dotfiles/bash/aliases
source ~/.dotfiles/bash/env

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/lauro/.sdkman"
[[ -s "/home/lauro/.sdkman/bin/sdkman-init.sh" ]] && source "/home/lauro/.sdkman/bin/sdkman-init.sh"

export GOPATH="/home/lauro/go"
export GO111MODULE="on"
export PATH="$HOME/.cargo/bin:$GOPATH/bin:/usr/local/go/bin:$PATH"
